### ISSUE TITLE
Simple SQL Query doesn't finish since Firebird 5.0.2

### ISSUE THREAD

**Issue by JohannAnhofer** [nakagami/pyfirebirdsql#118]
We have upgraded our Firebird Installation to the latest bugfix version 5.0.2 (Windows 11) 
And now even a simple select on a table doesn't work.
It locks up upon execution of the statement.
fbcore.py
`  def _op_response(self):
        b = self._recv_channel(4)`
Locks here 

called from _allocate_stmt
  `(h, oid, buf) = self.trans.connection._op_response()`

A simple sample to proof the lockup: Works with Firebird 5.0.1, Blocks with Firebird 5.0.2

```python
import firebirdsql as FB
try:   
    connection = FB.connect(host="localhost", database="c:\\databases\\employee.fdb", user="SYSDBA", password="masterkey")
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM rdb$database")
    response = cursor.fetchall()
    connection.commit()
    columnNames = [desc[0] for desc in cursor.description]
    users = []
    for row in response:
        rowDict = dict(list(zip(columnNames, row)))
        users.append(rowDict)
    connection.close()
    print(users)
except Exception as e:
    print(f"Error in SQL command execution: '{e}'")
```

**Comment by nakagami** [comment]
It seems to be the same as issue #115.
Is the server platform Windows?

**Comment by JohannAnhofer** [comment]
Yes, Windows 11 24H2 (10.0.26100.3194)

**Comment by jlbeluco** [comment]
Hello,
I don't know if this can help us. But I decided to try other libraries. And, in one of them, an error message was returned. Then I allowed myself to try something else.
See:

"Iraceback (most recent call last):
File "c:\Users\jlbel\Documents\MyPython\PyCli\app.py", line 4, in
import fdb
File "C:\Users\jlbel\Documents\MyPython\PyCli.venv\Lib\site-packages\fdb\ init .py", line 28, in

from fdb import gstat
File "C:\Users\jlbel\Documents\MyPython\PyCli.venv\Lib\site-packages\fdb\gstat.py", line 28, in

from locale import LC_ALL, LC_CTYPE, getlocale, setlocale, resetlocale
**ImportError:** cannot import name 'resetlocale' from 'locale' (C: \Users\jlbel\AppData\Local\Programs\Python
\Python313\Lib\locale.py). Did you mean: 'setlocale'?
"
In my case, to be able to continue, I simply removed the expression "resetlocale" and it worked without problems.

Could it be something similar in firebirdsql? I haven't had a chance to test it yet.

**Comment by nakagami** [comment]
It may have something to do with WireCrypto or zip compression.
Could you try firebirdsql.connect() with wire_crypt=False as an argument and see if you get the same error?

**Comment by JohannAnhofer** [comment]
wire_crypt=False doesn't help:
Firebird log shows: INET/inet_error: read errno = 10054

**Comment by nakagami** [comment]
Surely errno = 10054 is because the client has dropped the connection.
Authentication seems to have succeeded.

I can't find the cause in the release note.
https://firebirdsql.org/file/documentation/release_notes/html/en/5_0/rlsnotes50.html#rnfb50-general-improvements-v502

**Comment by JohannAnhofer** [comment]
> Surely errno = 10054 is because the client has dropped the connection. Authentication seems to have succeeded.
Yes, after waiting and nothing happens we have killed the task.
 
> I can't find the cause in the release note. https://firebirdsql.org/file/documentation/release_notes/html/en/5_0/rlsnotes50.html#rnfb50-general-improvements-v502
That's right, I've already looked into it and found no "breaking change".
But it's reproducible, I've switched the Server back and forth between 5.0.1 and 5.0.2.

**Comment by nakagami** [comment]
I have confirmed that the same result happens in Amazon WorkSpaces.

I don't have the correct fix yet, but the following fix should work on Windows + Firebird 5.0.2.
```
diff --git a/firebirdsql/fbcore.py b/firebirdsql/fbcore.py
index dbb2b7d..7186e87 100644
--- a/firebirdsql/fbcore.py
+++ b/firebirdsql/fbcore.py
@@ -672,6 +672,7 @@ class ConnectionResponseMixin:
         self.accept_architecture = bytes_to_bint(b[4:8])
         self.accept_type = bytes_to_bint(b[8:])
         self.lazy_response_count = 0
+        self.accept_type = ptype_lazy_send

         if op_code == self.op_cond_accept or op_code == self.op_accept_data:
             ln = bytes_to_bint(self._recv_channel(4))
```
If you have an environment where you can check, please do so.

**Comment by JohannAnhofer** [comment]
> I have confirmed that the same result happens in Amazon WorkSpaces.
> 
> I don't have the correct fix yet, but the following fix should work on Windows + Firebird 5.0.2.
> 
> ```
> diff --git a/firebirdsql/fbcore.py b/firebirdsql/fbcore.py
> index dbb2b7d..7186e87 100644
> --- a/firebirdsql/fbcore.py
> +++ b/firebirdsql/fbcore.py
> @@ -672,6 +672,7 @@ class ConnectionResponseMixin:
>          self.accept_architecture = bytes_to_bint(b[4:8])
>          self.accept_type = bytes_to_bint(b[8:])
>          self.lazy_response_count = 0
> +        self.accept_type = ptype_lazy_send
> 
>          if op_code == self.op_cond_accept or op_code == self.op_accept_data:
>              ln = bytes_to_bint(self._recv_channel(4))
> ```
> 
> If you have an environment where you can check, please do so.

Yes, this works! Now the query returns data!

**Comment by nakagami** [comment]
I think it is fixed in the current release 1.3.5, so please check it.

**Comment by JohannAnhofer** [comment]
> I think it is fixed in the current release 1.3.5, so please check it.

Yes, it works now! I hope it's backward compatible to Firebird < 5.0.2

**Comment by nakagami** [comment]
I think it's also backward compatible.

**Comment by mariuz** [comment]
Related discussion about Firebird 5.0.2 blob improvement https://groups.google.com/g/firebird-devel/c/t0chNMbvQ8E
